version: "3.8"

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    platform: linux/amd64
    restart: always
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=project # edit
    volumes:
      - ./docker/mysql:/var/lib/mysql:Z
      - ./docker/init:/docker-entrypoint-initdb.d